http:
  middlewares:
    security-headers:
      headers:
        browserXssFilter: true
        contentTypeNosniff: true
        frameDeny: false
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000
        customFrameOptionsValue: "SAMEORIGIN"
        customRequestHeaders:
          X-Forwarded-Proto: "https"
    
    cors-headers:
      headers:
        accessControlAllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        accessControlAllowOriginList:
          - "https://michaeloxo.tech"
        accessControlAllowCredentials: true
        accessControlMaxAge: 100
        addVaryHeader: true

    api-strip-prefix:
      stripPrefix:
        prefixes:
          - "/api"

    docs-strip-prefix:
      stripPrefix:
        prefixes:
          - "/docs"

    prometheus-strip-prefix:
      stripPrefix:
        prefixes:
          - "/prometheus"

    grafana-strip-prefix:
      stripPrefix:
        prefixes:
          - "/grafana"

    cadvisor-strip-prefix:
      stripPrefix:
        prefixes:
          - "/cadvisor"

    global-middleware:
      chain:
        middlewares:
          - security-headers
          - cors-headers
