apiVersion: v1
kind: Service
metadata:
  name: fastapi-backend-service
  labels:
    app: fastapi-backend
spec:
  selector:
    app: fastapi-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8080
      name: http-api
  type: ClusterIP