---
- name: Configure Server and Deploy Dockerized Stacks
  hosts: app_hosts
  become: true
  vars_files:
    - vars/main.yml

  roles:
    - common_setup
    - traefik_config
    - app_stack
    - monitoring_stack